project:
  type: website

website:
  title: "Untitled RPG"
  page-footer:
    center:
      - text: "About"
        href: about.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Phandalin"
          - phandalin/index.qmd
      - section: "Campaign"
        contents:
          - index.qmd
          - campaign/encounters.qmd
          - campaign/mines.qmd
      - section: "Rules"
        contents:
          - rules/abilities.qmd
          - rules/lineage.qmd
          - rules/training.qmd
          - rules/skills.qmd
          - rules/advancement.qmd
          - rules/equipment.qmd
          - rules/adventuring.qmd
          - rules/combat.qmd
          - rules/magic.qmd
          - rules/adversaries.qmd
  
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true



