project:
  type: website

website:
  title: "Untitled RPG"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Campaign"
        contents:
          - campaign/index.qmd
      - section: "Rules"
        contents:
          - rules/abilities.qmd
          - rules/lineage.qmd
          - rules/training.qmd
          - rules/skills.qmd
          - rules/advancement.qmd
          - rules/equipment.qmd
          - rules/adventuring.qmd
          - rules/combat.qmd
          - rules/magic.qmd
          - rules/adversaries.qmd
      - section: "About"
        contents:
          - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true



