---
title: "Abilities"
---

|Category|Name|Description|
|---|---|---|
|**Physical**|Muscle|strength and fitness|
||Agility|ability to respond quickly|
||Fortitude|health and pain tolerance|
|**Mental**|Acuity|perceptive senses (sight, hearing)|
||Insight|intuition and wisdom|
||Intellect|general intelligence and abstract thinking|
|**Will**|Courage|mental fortitude and resistance to fear|
||Magnetism|ability to attract others and inspire confidence|
||Spirit|capacity for and resistance to magical forces|

**Generating Abilities**
* Each ability has a bonus or penalty ranging from -5 to +5 
* Each ability starts at 0
* No more than one ability can be +4 to start
* A new character has 10 points to spend to adjust any ability up to a max of +3
* Reducing a starting ability allows the player to spend those points elsewhere
* No starting ability may be less than -2

*Optional Rules*
* For increased challenge, reduce starting points to 8 (and set min to -3)
* For decreased challenge, increase starting points to 12 (and set min to -1)

# Alternate
- 4 abilities scores: strength, agility, acuity, will